config/routes.rb
Rails.application.routes.draw do
  get 'speakers/search'
  get 'volunteers/pending'
  get 'volunteers/inactive', as: :inactive_volunteers
  get 'volunteers/active', as: :active_volunteers
  get 'speakers/:id', to: 'speakers#show', as: 'speaker'
  get 'org/:id', to: 'organizations#show', as: :org
  get 'user_meetings/pending', as: :pending_meetings
  get 'user_meetings', to: 'user_meetings#index', as: :user_meetings
  get 'user_meetings/admin', to: 'user_meetings#admin', as: :admin_user_meetings

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    patch ':id/activate', to: 'registrations#activate', as: 'activate_user'
    patch ':id/deactivate', to: 'registrations#deactivate', as: 'deactivate_user'
  end

  resources :volunteers

  resources :user_meetings_steps
  resources :localities do
    member do
      get 'report'
    end
    collection do
      get 'report_all'
    end
    resources :user_meetings do
      member do
        patch 'approve'
        patch 'deny'
        patch 'review'
      end
      collection do
        get 'admin'
      end
    end
  end

  get 'cukes', to: 'cukes#index', as: :cukes

  # Contact Form
  get 'contact' => 'contact_form#new'
  post 'contact' => 'contact_form#create'

  # Uses the 'high_voltage' gem. Modify app/views/pages/home.html.erb
  get 'pages/home'
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :user

  def inactive
    @confirmed_volunteers = User
      .where.not(confirmed_at: nil)
      .where(approved: false)
  end

  def active
    @confirmed_volunteers = User
      .where.not(confirmed_at: nil)
      .where(approved: true)
  end

  def show
    @volunteer = User.find params[:id]
  end

  def update
    @volunteer = User.find params[:id]
    if @volunteer.update_attributes(user_params)
      redirect_to :back,
                  notice: 'Volunteer was successfully updated'
    else
      render :active
    end
  end

  private

  def user_params
    params.require(:user).permit(roles: [])
  end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/active.html.erb
<% page_name 'Active Volunteers' %>
<div id="confirmed_volunteers" class='row'>
  <div class="col-lg-10 col-lg-offset-1">
    <h1 class="page-header">Active volunteers</h1>
    <table class='table table-striped table-bordered'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Actions</th>
          <th>Roles</th>
        </tr>
      </thead>
      <tbody>
        <% @confirmed_volunteers.each do |vol| %>
          <tr>
            <td>
              <%= vol.full_name %>
            </td>
            <td>
              <%= vol.email %>
            </td>
            <td>
              <%= button_to deactivate_user_path(vol), method: :patch,
                id: "deactivate_volunteer_#{vol.id}",
                class: 'btn btn-danger btn-xs',
                disabled: vol == current_user do %>
                <span class='glyphicon glyphicon-remove'></span> Deactivate
              <% end %>
            </td>
            <td id="volunteer_<%= vol.id %>_roles">
              <%= form_for vol, as: :volunteer, url: volunteer_path(vol) do |v| %>
                <% for role in [:trusted, :admin] %>
                  <label>
                    <%= check_box_tag "user[roles][]", role, vol.has_role?(role), id: "user_#{vol.id}_role_#{role}" %>
                    <%= role.to_s.humanize %>
                  </label>
                  &nbsp;
                <% end %>
                <%= hidden_field_tag "user[roles][]" %>
                <%= v.button as: :submit, class: 'btn btn-primary btn-xs' do %>
                  <span class='glyphicon glyphicon-ok'></span> Update
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/volunteers/inactive.html.erb
<% page_name 'Inactive Volunteers' %>
<div id="confirmed_volunteers" class='row'>
  <div class="col-lg-10 col-lg-offset-1">
    <h1 class="page-header">Inactive volunteers</h1>
    <table class='table table-striped table-bordered'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @confirmed_volunteers.each do |vol| %>
          <tr>
            <td>
              <%= vol.full_name %>
            </td>
            <td>
              <%= vol.email %>
            </td>
            <td>
              <%= link_to activate_user_path(vol), method: :patch,
                id: "activate_volunteer_#{vol.id}",
                class: 'btn btn-primary btn-xs' do %>
                <span class='glyphicon glyphicon-ok'></span> Activate
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/volunteers/show.html.erb
<% page_name "Volunteer #{@volunteer.full_name}" %>

<div class='row'>
  <div class='col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1 col-lg-10'>
    <h3 class="page-header"><%= @volunteer.full_name %></h3>
  </div>
</div>
<div class="row">
  <div class='col-md-5 col-md-offset-1 col-xs-5 col-xs-offset-1 col-lg-5'>
    <p><strong>Email</strong>: <%= mail_to @volunteer.email %></p>

    <p><strong>Phone</strong>: <%= @volunteer.phone_number %></p>

    <p><strong>Approved?</strong>: <%= @volunteer.approved? %></p>

    <p><strong>Role</strong>: <%= @volunteer.role %></p>

    <p><strong>Locality</strong>: <%= @volunteer.locality_id %></p>
  </div>

  <div class="col-md-5 col-xs-5 col-lg-5">
    <ul>
      <li>Set Role:</li>
      <li>Enable/Disable:</li>
    </ul>
  </div>
</div>
</div>