config/routes.rb
Rails.application.routes.draw do
  get 'speakers/search'
  get 'volunteers/pending'
  get 'volunteers/inactive', as: :inactive_volunteers
  get 'volunteers/active', as: :active_volunteers
  get 'speakers/:id', to: 'speakers#show', as: 'speaker'
  get 'org/:id', to: 'organizations#show', as: :org
  get 'user_meetings/pending', as: :pending_meetings
  get 'user_meetings', to: 'user_meetings#index', as: :user_meetings
  get 'user_meetings/admin', to: 'user_meetings#admin', as: :admin_user_meetings

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    patch ':id/activate', to: 'registrations#activate', as: 'activate_user'
    patch ':id/deactivate', to: 'registrations#deactivate', as: 'deactivate_user'
  end

  resources :volunteers

  resources :user_meetings_steps
  resources :localities do
    member do
      get 'report'
    end
    collection do
      get 'report_all'
    end
    resources :user_meetings do
      member do
        patch 'approve'
        patch 'deny'
        patch 'review'
      end
      collection do
        get 'admin'
      end
    end
  end

  get 'cukes', to: 'cukes#index', as: :cukes

  # Contact Form
  get 'contact' => 'contact_form#new'
  post 'contact' => 'contact_form#create'

  # Uses the 'high_voltage' gem. Modify app/views/pages/home.html.erb
  get 'pages/home'
end

app/models/locality.rb
class Locality < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :finders]
  has_many :user_meetings

  validates :name,
            :phone_number,
            :street_address,
            :city,
            :state_code,
            :country_code,
            :zip,
            :slug,
            presence: true
  validates :volunteer_needed,
            :invocations_conducted,
            inclusion: { in: [true, false] }
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :authenticate_user!,
                except: [:index, :show, :report, :report_all]
  load_and_authorize_resource except: [:report, :report_all, :index]
  helper_method :sort_column, :sort_direction
  respond_to :html

  def edit
    @locality = Locality.friendly.find params[:id]
    respond_with @locality
  end

  def index
    @localities = Locality.all
  end

  def new
    @locality = Locality.new params[:locality]
    respond_with @locality
  end

  def create
    @locality = Locality.new locality_params
    if @locality.save
      flash[:notice] = "#{@locality.name} locality successfully created"
    end
    respond_with @locality
  end

  def show
    @locality = Locality.friendly.find params[:id]
    @user_meetings = @locality
      .user_meetings
      .includes({ speaker: [:religion, :organization] }, :locality)
      .paginate(page: params[:page])
      .approved
      .order(sort_column + ' ' + sort_direction)
    respond_with @locality
  end

  def update
    @locality = Locality.friendly.find params[:id]
    if @locality.update_attributes(locality_params)
      flash[:notice] = 'Locality was successfully updated'
    end
    respond_with @locality
  end

  def report
    @user_meetings = locality_report(params[:id])
    @meeting_date = oldest_record(params[:id])
  end

  def report_all
    @user_meetings = locality_report(nil)
    @meeting_date = oldest_record(nil)
  end

  private

  def locality_report(id)
    meetings = UserMeeting
      .joins { [locality.outer, speaker.outer.religion.outer, user.outer] }
      .select('religions.name as religion, count(religions.name) as count')
      .where(invocation_conducted: 'Yes')
      .group('religions.name')
      .approved
      .order('2 DESC')

    return meetings unless id
    meetings.where { locality_id.eq id }
  end

  def oldest_record(id)
    meeting_date = UserMeeting
      .joins { [locality.outer, speaker.outer.religion.outer, user.outer] }
      .select('meeting_time')
      .where(invocation_conducted: 'Yes')
      .approved
      .order('meeting_time ASC')
      .limit(1)

    return meeting_date unless id
    meeting_date.where { locality_id.eq id }
  end

  private

  def locality_params
    params.require(:locality)
      .permit :name, :phone_number, :street_address, :country_code, :state_code,
              :city, :zip, :location_notes, :website_url, :volunteer_needed,
              :meeting_data_url, :meeting_schedule, :invocations_conducted,
              :contact_name, :contact_title, :contact_email, :contact_phone,
              :contact_street_address, :contact_city, :contact_country_code,
              :contact_state_code, :contact_zip, :contact_notes
  end

  def sort_column
    UserMeeting.column_names.include?(params[:sort]) ? params[:sort] : 'id'
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/views/localities/_form.html.erb
<%= form_for @locality, html: {class: 'form-vertical'} do |f| %>
  <h3><%= yield(:locality_heading) %></h3>
  <% if @locality.errors.any? %>
    <ul>
      <% @locality.errors.full_messages.each do |msg| %>
        <li class="field_with_errors"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Enter locality name' %>
  </div>
  <div class='form-group'>
    <%= f.label :street_address %>
    <%= f.text_field :street_address, class: 'form-control', placeholder: '123 Any St' %>
  </div>
  <div class='form-group'>
    <%= f.label :city %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.hidden_field :country_code, value: 'US' %>
    <%= f.label :state_code %>
    <% # subregion_select method from "carmen-rails" gem  %>
    <%= f.subregion_select :state_code, 'US', {}, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :zip %>
    <%= f.text_field :zip, size: 10, class: 'form-group' %>
  </div>
  <div class='form-group'>
    <%= f.label :phone_number %>
    <%= f.phone_field :phone_number, size: 20, class: 'form-group' %>
  </div>
  <div class='form-group'>
    <%= f.label :location_notes %>
    <%= f.text_area :location_notes, rows: 10, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :website_url %>
    <%= f.url_field :website_url, size: 20, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :volunteer_needed %>
    <div class='radio'>
      <label>
        <%= f.radio_button :volunteer_needed, true, value: true %>
        Yes
      </label>
    </div>
    <div class='radio'>
      <label>
        <%= f.radio_button :volunteer_needed, false, value: false %>
        No
      </label>
    </div>
  </div>
  <div class='form-group'>
    <%= f.label :meeting_data_url %>
    <%= f.url_field :meeting_data_url, size: 20, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :meeting_schedule %>
    <%= f.text_area :meeting_schedule, rows: 10, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :invocations_conducted %>
    <div class='radio'>
      <label>
        <%= f.radio_button :invocations_conducted, 'true' %>
        Yes
      </label>
    </div>
    <div class='radio'>
      <label>
        <%= f.radio_button :invocations_conducted, 'false' %>
        No
      </label>
    </div>
  </div>
  <h4>Locality Contact:</h4>
  <div class='form-group'>
    <%= f.label :contact_name %>
    <%= f.text_field :contact_name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :contact_title %>
    <%= f.text_field :contact_title, size: 5, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :contact_phone %>
    <%= f.telephone_field :contact_phone, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :contact_email %>
    <%= f.email_field :contact_email, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :contact_street_address %>
    <%= f.text_field :contact_street_address, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :contact_city %>
    <%= f.text_field :contact_city, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.hidden_field :contact_country_code, value: 'US' %>
    <%= f.label :contact_state_code, 'State' %>
    <%= f.subregion_select :contact_state_code, 'US', {}, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :contact_zip %>
    <%= f.text_field :contact_zip, size: 10, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :contact_notes %>
    <%= f.text_area :contact_notes, rows: 10, class: 'form-control' %>
  </div>
  <%= f.button type: 'submit', class: 'btn btn-default btn-lg pull-right' %>
<% end %>

app/views/localities/edit.html.erb
<% page_name @locality.name %>
<% content_for :locality_class do %>
  active
<% end %>

<% content_for :locality_heading do %>
  Editing <span class="locality"><%= @locality.name %></span>
<% end %>

<div class='row'>
  <div class='col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2 authform'>
    <%= render 'form' %>
  </div>
</div>

app/views/localities/index.html.erb
<% page_name 'Localities' %>

<div class="row">
  <div class="col-lg-10 col-lg-offset-1 col-md-12">
    <h1 class="page-header">Locations</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-10 col-lg-offset-1 col-md-12">
    <ul>
      <% @localities.each do |locality| %>
        <li><%= link_to locality.name, locality_path(locality) %></li>
      <% end %>
    </ul>

    <% if user_signed_in? && current_user.has_role?(:admin) %>
      <p><%= link_to "Add a new locality!", new_locality_path %></p>
    <% end %>
  </div>
</div>

app/views/localities/new.html.erb
<% page_name 'New Locality' %>

<div class='row'>
  <div class='col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2 authform'>
    <%= render 'form' %>
  </div>
</div>

app/views/localities/show.html.erb
<% page_name @locality.name %>
<% content_for :scripts do %>
  <%= javascript_include_tag 'jsapi','charts' %>
<% end %>

<% render 'layouts/pew_footnote' %>

<div class="row">
  <div class="col-lg-10 col-lg-offset-1 col-md-12">
    <h1 class="page-header" data-id="<%= @locality.id %>"><%= @locality.name %></h1>
    <p><strong>City</strong> <%= @locality.city %></p>
    <ul class="locality_nav" role="navigation">
      <% if user_signed_in? && current_user.has_role?(:admin) %>
        <li><%= link_to "Edit this locality", edit_locality_path(@locality) %></li>
      <% end %>
      <li><%= link_to "Submit a new meeting", new_locality_user_meeting_path(@locality) %></li>
    </ul>
  </div>
</div>
<div class="row">
</div>

<div class="row">
  <div class="col-lg-4 col-lg-offset-1 col-md-6 col-sm-6 graph">
    <h4>Florida Population</h4>
    <small>(Source:
      <a href="http://www.pewforum.org/2008/06/23/us-religious-landscape-survey-resources/" target="_blank">Pew
        Research</a>*)
    </small>
    <div id="population_chart"></div>
  </div>

  <div class="col-lg-4 col-lg-offset-1 col-md-6 col-sm-6 graph">
    <h4>InvocationsOnline Summary</h4>
    <small>(<%= @locality.name %>) <%= @locality_date %></small>
    <div id="invocations_chart"></div>
  </div>

  <div class="col-lg-2 col-lg-offset-1 locality_nav">
    <!--Todo Only show these links provided a user has the respective permissions for this locality-->
  </div>
</div>

<div class='row'>
  <div class='col-lg-10 col-lg-offset-1 col-md-12'>
    <h3>Meeting Data</h3>
    <% content_for :scripts do %>
      <%= javascript_include_tag 'meetingApproval' %>
    <% end %>
    <div class="text-center"><%= will_paginate @user_meetings %></div>
    <table class="table table-hover">
      <thead>
      <tr>
        <th><%= sortable 'id', 'Meeting ID' %></th>
        <th><%= sortable 'meeting_time', 'Meeting Time' %></th>
        <th>Religion</th>
        <th>Speaker</th>
        <th>Organization</th>
        <th class="text-center">Action</th>
      </tr>
      </thead>
      <tbody>
      <%= render partial: 'user_meetings/user_meeting', collection: @user_meetings %>
      </tbody>
    </table>
    <div class="text-center"><%= will_paginate @user_meetings %></div>
  </div>
</div>