config/routes.rb
Rails.application.routes.draw do
  get 'speakers/search'
  get 'volunteers/pending'
  get 'volunteers/inactive', as: :inactive_volunteers
  get 'volunteers/active', as: :active_volunteers
  get 'speakers/:id', to: 'speakers#show', as: 'speaker'
  get 'org/:id', to: 'organizations#show', as: :org
  get 'user_meetings/pending', as: :pending_meetings
  get 'user_meetings', to: 'user_meetings#index', as: :user_meetings
  get 'user_meetings/admin', to: 'user_meetings#admin', as: :admin_user_meetings

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    patch ':id/activate', to: 'registrations#activate', as: 'activate_user'
    patch ':id/deactivate', to: 'registrations#deactivate', as: 'deactivate_user'
  end

  resources :volunteers

  resources :user_meetings_steps
  resources :localities do
    member do
      get 'report'
    end
    collection do
      get 'report_all'
    end
    resources :user_meetings do
      member do
        patch 'approve'
        patch 'deny'
        patch 'review'
      end
      collection do
        get 'admin'
      end
    end
  end

  get 'cukes', to: 'cukes#index', as: :cukes

  # Contact Form
  get 'contact' => 'contact_form#new'
  post 'contact' => 'contact_form#create'

  # Uses the 'high_voltage' gem. Modify app/views/pages/home.html.erb
  get 'pages/home'
end

app/models/user_meeting.rb
class UserMeeting < ActiveRecord::Base
  include AASM

  self.per_page = 10

  aasm do
    state :pending, initial: true
    state :approved
    state :denied
    state :reviewed

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :deny do
      transitions from: :pending, to: :denied
    end

    event :review do
      transitions from: :pending, to: :reviewed
    end
  end

  sifter :state_is do |meeting_state|
    aasm_state.eq meeting_state
  end

  before_create :check_user_role

  # store new version when any attribute is changed
  # see https://github.com/airblade/paper_trail for info
  has_paper_trail

  belongs_to :user
  belongs_to :locality
  belongs_to :speaker

  validates :meeting_type,
            :meeting_time,
            :invocation_conducted,
            :user,
            :locality,
            presence: true

  accepts_nested_attributes_for :speaker

  def check_user_role
    approve if user.has_role? :trusted
  end

  def send_approval_request
    MeetingMailer.approval_request(self, aasm.to_state.to_s).deliver_later
  end
end

app/controllers/user_meetings_controller.rb
class UserMeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_locality, only: [:new, :create, :edit, :update]
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction
  respond_to :html

  def index
    @user_meetings = current_user
      .user_meetings
      .includes({ speaker: [:religion, :organization] }, :locality)
      .paginate(page: params[:page])
      .order(sort_column + ' ' + sort_direction)
    respond_with @user_meetings
  end

  def admin
    return unless current_user.has_role?(:admin)
    @user_meetings = UserMeeting
      .includes({ speaker: [:religion, :organization] }, :locality)
      .paginate(page: params[:page])
      .pending.order(sort_column + ' ' + sort_direction)
    respond_with @user_meetings
  end

  def new
    @user_meeting = current_user.user_meetings.build params[:user_meeting]
    @user_meeting.build_speaker
    respond_with @user_meeting
  end

  def show
    @user_meeting = UserMeeting.find(params[:id])
    respond_with @user_meeting
  end

  def approve
    # Need some kind of validation?
    @user_meeting = UserMeeting.find(params[:id])
    @user_meeting.approve!
    MeetingMailer.approval_request(@user_meeting).deliver_later
    redirect_to admin_user_meetings_path, notice: t('user_meeting.admin.approved')
  end

  def deny
    @user_meeting = UserMeeting.find params[:id]
    @user_meeting.deny!
    MeetingMailer.approval_request(@user_meeting).deliver_later
    redirect_to admin_user_meetings_path, notice: t('user_meeting.admin.denied')
  end

  def review
    @user_meeting = UserMeeting.find params[:id]
    @user_meeting.review!
    MeetingMailer.approval_request(@user_meeting).deliver_later
    redirect_to admin_user_meetings_path, notice: t('user_meeting.admin.reviewed')
  end

  def create
    @user_meeting = current_user.user_meetings.build params_with_locality
    @user_meeting.speaker =
      find_or_create_speaker if user_meeting_params[:speaker_attributes]

    flash[:notice] = get_flash(@user_meeting) if @user_meeting.save
    respond_with @locality, @user_meeting, location: locality_path(@locality)
  end

  def edit
    @user_meeting = UserMeeting.find params[:id]
  end

  def update
    @user_meeting = UserMeeting.find params[:id]
    if @user_meeting.update_attributes(params_with_locality)
      unless current_user.has_role?(:trusted) || current_user.has_role?(:admin)
        @user_meeting.aasm_state = 'pending'
        @user_meeting.save
      end
      flash[:notice] = 'Meeting was successfully updated'
    end
    redirect_to @locality
  end

  private

  def find_locality
    @locality = Locality.friendly.find params[:locality_id]
  end

  def path_for_meetings
    return user_meetings_path unless current_user.has_role?(:admin)
    admin_user_meetings_path
  end

  def find_or_create_speaker
    Speaker.find_by(name: user_meeting_params[:speaker_attributes][:name]) ||
      Speaker.new(user_meeting_params[:speaker_attributes])
  end

  def get_flash(meeting)
    if meeting.pending?
      t('user_meeting.created_pending')
    else
      t('user_meeting.created_approved')
    end
  end

  def report
    @user_meeting = UserMeeting.all
    respond_to do |format|
      format.json { render json: @user_meeting }
    end
  end

  def user_meeting_params
    params.require(:user_meeting)
      .permit :id, :meeting_type, :meeting_time, :invocation_conducted,
              :pledge_before, :asked_to_stand, :speaker_preached,
              :speaker_preached_explanation, :speaker_praised,
              :speaker_praised_explanation, :concerns, :attachment,
              :street_address, :meeting_url, :minutes_url,
              :agenda_url, :media_url, :user_id, :locality_id,
              speaker_attributes: [:id, :name, :honorific, :religion_id,
                                   :denomination_id,
                                   organization_attributes: [:id, :name]]
  end

  def params_with_locality
    user_meeting_params.merge locality_id: @locality.id
  end

  def sort_column
    UserMeeting.column_names.include?(params[:sort]) ? params[:sort] : 'meeting_time'
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'desc'
  end

  def prev_count(records_per_page)
    if record_offset == 0
      record_offset
    elsif record_offset > 0 && record_offset < 10
      0
    else
      record_offset - records_per_page
    end
  end

  def record_offset
    params[:offset].nil? ? 0 : params[:offset].to_i
  end
end

app/helpers/user_meetings_helper.rb
module UserMeetingsHelper
  def meeting_types
    [
      %w(Regular Regular),
      %w(Special Special),
      %w(Other Other)
    ]
  end

  def invocation_options
    [
      %w(Yes Yes),
      %w(No No),
      ['Moment of silence', 'Moment of silence']
    ]
  end

  def pledge_options
    [
      ['Immediately before', 'Immediately before'],
      ['Immediately after', 'Immediately after'],
      %w(Neither Neither),
      %w(Unknown Unknown)
    ]
  end

  def stand_options
    [
      ['Yes, by official/employee', 'Yes, by official/employee'],
      ['Yes, by speaker', 'Yes, by speaker'],
      %w(Both Both),
      %w(Neither Neither)
    ]
  end

  def speaker_options
    [
      ['Yes, Explain', 'Yes, Explain'],
      %w(No No),
      %w(Unknown Unknown)
    ]
  end

  def get_meeting_id_link(user_meeting, link_name)
    if current_user.nil?
      user_meeting.id
    elsif  current_user.has_role?(:admin)
      link_to(
        link_name, locality_user_meeting_path(user_meeting.locality, user_meeting))
    else
      user_meeting.id
    end
  end
end

app/views/user_meetings/_meeting_table.html.erb
<% content_for :scripts do %>
  <%= javascript_include_tag 'meetingApproval' %>
<% end %>

<table class="table table-hover">
  <thead>
  <tr>
    <th><%= sortable 'id', 'Meeting ID' %></th>
    <th><%= sortable 'meeting_time', 'Meeting Time' %></th>
    <th><%= sortable 'pledge_before', 'Before Pledge?' %></th>
    <th><%= sortable 'asked_to_stand', 'Asked to Stand?' %></th>
    <th><%= sortable 'speaker_preached', 'Speaker Preach?' %></th>
    <th><%= sortable 'speaker_praised', 'Speaker Praised?' %></th>
    <th class="text-center action-col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @user_meetings.each_with_index do |m, i| %>
    <tr class="<%= (i % 2 == 0) ? 'even' : 'odd' %>">
      <td><%= current_user.has_role?(:admin) ? link_to( m.id, user_meeting_path(m)) : m.id %></td>
      <td><%= fulltime(m.meeting_time) %></td>
      <td><%= m.pledge_before %></td>
      <td><%= m.asked_to_stand %></td>
      <td><%= m.speaker_preached %></td>
      <td><%= m.speaker_praised %></td>
      <td>
        <div class="btn-group">
          <%= button_to user_meeting_path(m), method: :get, id: "show_meeting_#{m.id}", class: 'btn btn-primary btn-xs hide hide-panel' do %>
            <span class="glyphicon glyphicon-eye-open"></span> More Info
          <% end %>
          <% if current_user.has_role?(:admin) %>
            <%= button_to approve_user_meeting_path(m), method: :patch, id: "approve_meeting_#{m.id}", class: 'btn btn-success btn-xs' do %>
              <span class="glyphicon glyphicon-ok"></span> Approve
            <% end %>
            <%= button_to review_user_meeting_path(m), method: :patch, id: "review_meeting_#{m.id}", class: 'btn btn-warning btn-xs' do %>
              <span class='glyphicon glyphicon-exclamation-sign'></span> In Review
            <% end %>
            <%= button_to deny_user_meeting_path(m), method: :patch, id: "deny_meeting_#{m.id}", class: "btn btn-danger btn-xs" do %>
              <span class="glyphicon glyphicon-remove"></span> Deny
            <% end %>
          <% end %>
        </div>
      </td>
    </tr>
    <tr class="toggleable">
      <td colspan="7">
        <div class="slide-panel">
          <div class="col-lg-3">
            <h4>Meeting Links</h4>
            <ul>
              <li><%= current_user.has_role?(:admin) ? link_to( 'Single record view', user_meeting_path(m)) : m.id %></li>
              <li><%= get_meeting_links 'Meeting', m.meeting_url %></li>
              <li><%= get_meeting_links 'Minutes', m.minutes_url %></li>
              <li><%= get_meeting_links 'Agenda', m.agenda_url %></li>
              <li><%= get_meeting_links 'Media', m.media_url %></li>
              <li><%= get_meeting_links 'Attachment', m.attachment %></li>
            </ul>
          </div>
          <div class="col-lg-5">
            <h4>Explanations</h4>
            <h5>Preached</h5>

            <p><%= m.speaker_preached_explanation %></p>

            <h5>Praised</h5>

            <p><%= m.speaker_praised_explanation %></p>

            <h5>Concerns</h5>

            <p><%= m.concerns %></p>
          </div>
          <div class="col-lg-3">
            <h4>Other</h4>
            <ul>
              <li>Invocation: <%= m.invocation_conducted %></li>
              <li>Pending: <%= m.pending? %></li>
              <li>Submitted by: <%= m.user.full_name %></li>
              <li>Locality: <%= link_to m.locality.name, locality_path(m.locality) %></li>
              <li>Meeting Type: <%= m.meeting_type %></li>
              <li>Speaker: <%= link_to m.speaker.name, speaker_path(m.speaker) %></a></li>
              <li>Organization: <%= get_obj_name(m.speaker.organization) %> </li>
              <li>Religion: <%= get_obj_name(m.speaker.religion) %> </li>
            </ul>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/user_meetings/_radio_buttons.html.erb
<% radio_options.each do |opt| %>
  <div class='radio'>
    <label>
      <%= f.radio_button field, opt %>
      <%= opt.capitalize %>
    </label>
  </div>
<% end %>

app/views/user_meetings/_user_meeting.html.erb
<% cache user_meeting do %>
  <tr class="<%= (user_meeting_counter % 2 ==0) ? 'even' : 'odd' %>" id="table_data">
    <td><%= get_meeting_id_link(user_meeting, user_meeting.id) %></td>
    <td><%= fulltime(user_meeting.meeting_time) %></td>
    <td><%= get_obj_name(user_meeting.speaker.religion) %></td>
    <td><%= user_meeting.speaker.name %></td>
    <td><%= get_obj_name(user_meeting.speaker.organization) %></td>
    <td>
      <div class="btn-group">
        <%= button_to locality_user_meeting_path(user_meeting.locality, user_meeting), method: :get, id: "show_meeting_#{user_meeting.id}", class: 'btn btn-primary btn-xs hide hide-panel' do %>
          <span class="glyphicon glyphicon-eye-open"></span> More Detail
        <% end %>
        <% if user_signed_in? %>
          <% if current_user.has_role?(:admin) %>
            <%= link_to(edit_locality_user_meeting_path(user_meeting.locality, user_meeting), class: 'label label-info', role: 'button') do %>
              <span class="glyphicon glyphicon-pencil"></span> Edit
            <% end %>
          <% end %>
        <% end %>
      </div>
    </td>
  </tr>
  <tr class="toggleable">
    <td colspan="7">
      <div class="slide-panel">
        <div class="col-lg-3">
          <h4>Meeting Links</h4>
          <ul>
            <li><%= get_meeting_id_link(user_meeting, 'Single Record View') %></li>
            <li><%= get_meeting_links 'Meeting', user_meeting.meeting_url %></li>
            <li><%= get_meeting_links 'Minutes', user_meeting.minutes_url %></li>
            <li><%= get_meeting_links 'Agenda', user_meeting.agenda_url %></li>
            <li><%= get_meeting_links 'Media', user_meeting.media_url %></li>
            <li><%= get_meeting_links 'Attachment', user_meeting.attachment %></li>
          </ul>
        </div>
      </div>
    </td>
  </tr>
  <tr class="toggleable">
    <td colspan="7">
      <div class="slide-panel">
        <div class="col-lg-3">
          <h4>Meeting Links</h4>
          <ul>
            <li><%= get_meeting_id_link(user_meeting, 'Single Record View') %></li>
            <li><%= get_meeting_links 'Meeting', user_meeting.meeting_url %></li>
            <li><%= get_meeting_links 'Minutes', user_meeting.minutes_url %></li>
            <li><%= get_meeting_links 'Agenda', user_meeting.agenda_url %></li>
            <li><%= get_meeting_links 'Media', user_meeting.media_url %></li>
            <li><%= get_meeting_links 'Attachment', user_meeting.attachment %></li>
          </ul>
        </div>
        <div class="col-lg-5">
          <h4>Explanations</h4>
          <ul>
            <li><strong>Preached:</strong>
              <p><%= user_meeting.speaker_preached_explanation %></p>
            </li>
            <li><strong>Praised:</strong>
              <p><%= user_meeting.speaker_praised_explanation %></p>
            </li>
            <li><strong>Concerns:</strong>
              <p><%= user_meeting.concerns %></p>
            </li>
          </ul>
        </div>
        <div class="col-lg-3">
          <h4>Other</h4>
          <ul>
            <li><strong>Invocation:</strong> <%= user_meeting.invocation_conducted %></li>
            <li><strong>Pending:</strong> <%= user_meeting.pending? %></li>
            <li><strong>Submitted by:</strong> <%= user_meeting.user.full_name %></li>
            <li><strong>Locality:</strong> <%= link_to user_meeting.locality.name, locality_path(user_meeting.locality) %></li>
            <li><strong>Meeting Type:</strong> <%= user_meeting.meeting_type %></li>
            <li><strong>Speaker:</strong> <%= link_to user_meeting.speaker.name, speaker_path(user_meeting.speaker) %></a></li>
            <li><strong>Organization:</strong> <%= get_obj_name(user_meeting.speaker.organization) %> </li>
            <li><strong>Religion:</strong> <%= get_obj_name(user_meeting.speaker.religion) %> </li>
          </ul>
        </div>
      </div>
    </td>
  </tr>
<% end %>

app/views/user_meetings/admin.html.erb
<% page_name 'Meeting Data' %>


<div class="row">
  <div class="col-lg-10 col-lg-offset-1 col-md-12">
    <h1 class="page-header">Meeting Data</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-10 col-lg-offset-1 col-md-12">
    <% content_for :scripts do %>
      <%= javascript_include_tag 'meetingApproval' %>
    <% end %>
    <div class="text-center"><%= will_paginate @user_meetings%></div>
    <table class="table table-hover">
      <thead>
      <tr>
        <th><%= sortable 'id', 'Meeting ID' %></th>
        <th><%= sortable 'meeting_time', 'Meeting Time' %></th>
        <th>Religion</th>
        <th>Speaker</th>

        <th class="text-center action-col">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @user_meetings.each_with_index do |m, i| %>
        <tr class="<%= (i % 2 == 0) ? 'even' : 'odd' %>">
          <td><%= current_user.has_role?(:admin) ? link_to(m.id, locality_user_meeting_path(m.locality, m)) : m.id %></td>
          <td><%= fulltime(m.meeting_time) %></td>
          <td><%= get_obj_name(m.speaker.religion) %></td>
          <td><%= m.speaker.name %></td>
          <td>
            <div class="btn-group">
              <%= button_to locality_user_meeting_path(m.locality, m), method: :get, id: "show_meeting_#{m.id}", class: 'btn btn-primary btn-xs hide hide-panel' do %>
                <span class="glyphicon glyphicon-eye-open"></span> More Info
              <% end %>
              <% if current_user.has_role?(:admin) %>
                <%= button_to approve_locality_user_meeting_path(m.locality, m), method: :patch, id: "approve_meeting_#{m.id}", class: 'btn btn-success btn-xs' do %>
                  <span class="glyphicon glyphicon-ok"></span> Approve
                <% end %>
                <%= button_to review_locality_user_meeting_path(m.locality, m), method: :patch, id: "review_meeting_#{m.id}", class: 'btn btn-warning btn-xs' do %>
                  <span class='glyphicon glyphicon-exclamation-sign'></span> In Review
                <% end %>
                <%= button_to deny_locality_user_meeting_path(m.locality, m), method: :patch, id: "deny_meeting_#{m.id}", class: "btn btn-danger btn-xs" do %>
                  <span class="glyphicon glyphicon-remove"></span> Deny
                <% end %>
                <%= link_to(edit_locality_user_meeting_path(m.locality, m), class: 'label label-info', role: 'button') do %>
                  <span class="glyphicon glyphicon-pencil"></span> Edit
                <% end %>
              <% end %>
            </div>
          </td>
        </tr>
        <tr class="toggleable">
          <td colspan="7">
            <div class="slide-panel">
              <div class="col-lg-3">
                <h4>Meeting Links</h4>
                <ul>
                  <li><%= current_user.has_role?(:admin) ? link_to('Single record view', locality_user_meeting_path(m.locality, m)) : m.id %></li>
                  <li><%= get_meeting_links 'Meeting', m.meeting_url %></li>
                  <li><%= get_meeting_links 'Minutes', m.minutes_url %></li>
                  <li><%= get_meeting_links 'Agenda', m.agenda_url %></li>
                  <li><%= get_meeting_links 'Media', m.media_url %></li>
                  <li><%= get_meeting_links 'Attachment', m.attachment %></li>
                </ul>
              </div>
              <div class="col-lg-5">
                <h4>Explanations</h4>
                <ul>
                  <li><strong>Preached:</strong>
                    <p><%= m.speaker_preached_explanation %></p>
                  </li>
                  <li><strong>Praised:</strong>
                    <p><%= m.speaker_praised_explanation %></p>
                  </li>
                  <li><strong>Concerns:</strong>
                    <p><%= m.concerns %></p>
                  </li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h4>Other</h4>
                <ul>
                  <li>Invocation: <%= m.invocation_conducted %></li>
                  <li>Pending: <%= m.pending? %></li>
                  <li>Submitted by: <%= m.user.full_name %></li>
                  <li>Locality: <%= link_to m.locality.name, locality_path(m.locality) %></li>
                  <li>Meeting Type: <%= m.meeting_type %></li>
                  <li>Speaker: <%= link_to m.speaker.name, speaker_path(m.speaker) %></a></li>
                  <li>Organization: <%= get_obj_name(m.speaker.organization) %> </li>
                  <li>Religion: <%= get_obj_name(m.speaker.religion) %> </li>
                </ul>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="text-center"><%= will_paginate @user_meetings%></div>
  </div>
</div>

app/views/user_meetings/index.html.erb
<% page_name 'Meeting Data' %>


<div class="row">
  <div class="col-lg-10 col-lg-offset-1 col-md-12">
    <h1 class="page-header">Meeting Data</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-10 col-lg-offset-1 col-md-12">
    <% content_for :scripts do %>
      <%= javascript_include_tag 'meetingApproval' %>
    <% end %>
    <div class="text-center"><%= will_paginate @user_meetings %></div>
    <table class="table table-hover">
      <thead>
      <tr>
        <th><%= sortable 'id', 'Meeting ID' %></th>
        <th><%= sortable 'meeting_time', 'Meeting Time' %></th>
        <th>Religion</th>
        <th>Speaker</th>
        <th>Organization</th>
        <th class="text-center">Action</th>
      </tr>
      </thead>
      <tbody>
      <%= render @user_meetings %>
      </tbody>
    </table>
    <div class="text-center"><%= will_paginate @user_meetings %></div>
  </div>
</div>

app/views/user_meetings/pending.html.erb
<h1>User Meeetings</h1>
<div id='pending_meetings'>
  <table>
  </table>
</div>

app/views/user_meetings/show.html.erb
<% page_name "Meeting #{@user_meeting.id}" %>
<div class='row'>
  <div class='col-lg-10 col-lg-offset-1'>
    <h3 class="page-header">Showing Meeting <%= @user_meeting.id %></h3>
    <p><%= link_to(raw('<span class="glyphicon glyphicon-arrow-left"></span> Back to list'), :back ) %></p>
    <table class="table table-bordered table-striped">
      <thead>
      <th width="25%">Field</th>
      <th>Value</th>
      </thead>
      <tbody>
      <tr>
        <th>Meeting ID</th>
        <td>
          <%= @user_meeting.id %>
        </td>
      </tr>
      <tr>
        <th>Meeting Time</th>
        <td>
          <%= fulltime(@user_meeting.meeting_time) %>
        </td>
      </tr>
      <tr>
        <th>Was an incvocation conducted?</th>
        <td>
          <%= @user_meeting.invocation_conducted %>
        </td>
      </tr>
      <tr>
        <th>Were people asked to pldege?</th>
        <td>
          <%= @user_meeting.pledge_before %>
        </td>
      </tr>
      <tr>
        <th>Were people asked to stand?</th>
        <td>
          <%= @user_meeting.asked_to_stand %>
        </td>
      </tr>
      <tr>
        <th>Did the speaker preach?</th>
        <td>
          <%= @user_meeting.speaker_preached %>
        </td>
      </tr>
      <tr>
        <th>Explanation</th>
        <td>
          <%= @user_meeting.speaker_preached_explanation %>
        </td>
      </tr>
      <tr>
        <th>Was the speaker praised?</th>
        <td>
          <%= @user_meeting.speaker_praised %>
        </td>
      </tr>
      <tr>
        <th>Explanation</th>
        <td>
          <%= @user_meeting.speaker_praised_explanation %>
        </td>
      </tr>
      <tr>
        <th>Meeting Status</th>
        <td>
          <%= @user_meeting.aasm_state %>
        </td>
      </tr>
      <!--todo pull in submitter name-->
      <tr>
        <th>Submitter</th>
        <td>
          <%= link_to @user_meeting.user.full_name, volunteer_path(@user_meeting.user_id) %>
        </td>
      </tr>
      <tr>
        <th>Database create date</th>
        <td>
          <%= fulltime(@user_meeting.created_at)%>
        </td>
      </tr>
      <tr>
        <th>Last updated</th>
        <td>
          <%= fulltime(@user_meeting.updated_at) %>
        </td>
      </tr>
      <!--todo pull in locality name-->
      <tr>
        <th>Locality</th>
        <td>
          <%= link_to @user_meeting.locality.name, locality_path(@user_meeting.locality_id) %>
        </td>
      </tr>
      <tr>
        <th>Meeting type</th>
        <td>
          <%= @user_meeting.meeting_type %>
        </td>
      </tr>
      <tr>
        <th>Meeting address</th>
        <td>
          <%= @user_meeting.street_address %>
        </td>
      </tr>
      <!--todo update to use speaker name and info-->
      <tr>
        <th>Speaker</th>
        <td>
          <%= link_to @user_meeting.speaker.name, speaker_path(@user_meeting.speaker_id) %>
        </td>
      </tr>
      <tr>
        <th>Concerns</th>
        <td>
          <%= @user_meeting.concerns %>
        </td>
      </tr>
      <tr>
        <th>Meeting URL</th>
        <td>
          <%= get_meeting_links 'Meeting URL', @user_meeting.meeting_url %>
        </td>
      </tr>
      <tr>
        <th>Minutes URL</th>
        <td>
          <%= get_meeting_links 'Minutes URL', @user_meeting.minutes_url %>
        </td>
      </tr>
      <tr>
        <th>Agenda URL</th>
        <td>
          <%= get_meeting_links 'Agenda URL', @user_meeting.agenda_url %>
        </td>
      </tr>
      <tr>
        <th>Media URL</th>
        <td>
          <%= get_meeting_links 'Media URL', @user_meeting.media_url %>
        </td>
      </tr>
      <tr>
        <th>Attachment</th>
        <td>
          <%= get_meeting_links 'Attachment', @user_meeting.attachment %>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</div>