config/routes.rb
Rails.application.routes.draw do
  get 'speakers/search'
  get 'volunteers/pending'
  get 'volunteers/inactive', as: :inactive_volunteers
  get 'volunteers/active', as: :active_volunteers
  get 'speakers/:id', to: 'speakers#show', as: 'speaker'
  get 'org/:id', to: 'organizations#show', as: :org
  get 'user_meetings/pending', as: :pending_meetings
  get 'user_meetings', to: 'user_meetings#index', as: :user_meetings
  get 'user_meetings/admin', to: 'user_meetings#admin', as: :admin_user_meetings

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    patch ':id/activate', to: 'registrations#activate', as: 'activate_user'
    patch ':id/deactivate', to: 'registrations#deactivate', as: 'deactivate_user'
  end

  resources :volunteers

  resources :user_meetings_steps
  resources :localities do
    member do
      get 'report'
    end
    collection do
      get 'report_all'
    end
    resources :user_meetings do
      member do
        patch 'approve'
        patch 'deny'
        patch 'review'
      end
      collection do
        get 'admin'
      end
    end
  end

  get 'cukes', to: 'cukes#index', as: :cukes

  # Contact Form
  get 'contact' => 'contact_form#new'
  post 'contact' => 'contact_form#create'

  # Uses the 'high_voltage' gem. Modify app/views/pages/home.html.erb
  get 'pages/home'
end

app/views/layouts/_messages.html.erb
<div class="col-lg-10 col-lg-offset-1 col-md-12">
<%# Rails flash messages styled for Bootstrap 3.0 %>
  <% if user_signed_in? %>
    <% unless current_user.approved? %>
      <div class='alert alert-danger'>
        <%= content_tag :div, t('devise.registrations.signed_up_but_not_approved'), id: 'flash_unapproved' %>
      </div>
    <% end %>
  <% end %>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar">
  <div class="">
    <div class="navbar-header">
      <%= link_to('Invocations Online', root_path, class: 'navbar-brand text-hide', id: 'logo') %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right nav-pills" role="navigation">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

  <li class="<%= 'active' if current_page? root_path %>"><%= link_to 'Home', root_path %></li>
  <li class="<%= 'active' if current_page? page_path('moreinfo') %>"><%= link_to 'More Info', page_path('moreinfo') %></li>
  <li class="<%= 'active' if current_page? page_path('volunteer') or current_page? new_user_registration_path %>"><%= link_to 'Volunteer', page_path('volunteer') %></li>
  <li class="<%= 'active' if current_page? page_path('help')  %>"><%= link_to 'Help & FAQs', page_path('help') %></li>
  <li class="<%= 'active' if current_page? localities_path %>"> <%= link_to 'Locations', localities_path %></li>
<% if user_signed_in? %>
  <% if current_user.has_role?(:admin) %>
    <li class="dropdown" id="adminMenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <% pending_count =  pending_meeting_count %>
        <% if pending_count > 0 %>
          <span class="glyphicon glyphicon-flag" aria-hidden="true" style="color: #DA3B21;"></span>
        <% end %>
        Adminstration
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="adminMenu">
        <li class="<%= 'active' if current_page? admin_user_meetings_path %>">
          <%= link_to admin_user_meetings_path do %>
            Administer Submissions
            <% if pending_count > 0 %>
              <%= content_tag(:span, pending_count, :class => "badge") %>
            <% end %>
          <% end %>
        </li>
        <li role="presentation" class="divider"></li>
        <li class="<%= 'active' if current_page? active_volunteers_path %>"><%= link_to 'Active Volunteers', active_volunteers_path %></li>
        <li class="<%= 'active' if current_page? inactive_volunteers_path %>"><%= link_to 'Inactive Volunteers', inactive_volunteers_path %></li>
        <li role="presentation" class="divider"></li>
        <li><%= link_to 'Cukes', cukes_path %></li>
      </ul>
    </li>
  <% end %>
  <li class="dropdown" id="accountMenu">
    <a data-toggle="dropdown" href="#">Account <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="accountMenu">
      <li class="<%= 'active' if current_page? user_meetings_path %>"><%= link_to 'My Meetings', user_meetings_path %></li>
      <li class="<%= 'active' if current_page? edit_user_registration_path %>"><%= link_to 'Edit Account', edit_user_registration_path %></li>
      <li><%= link_to 'Log out', destroy_user_session_path, :method=>'delete' %></li>
    </ul>
  </li>
<% else %>
  <li><%= link_to 'Log in', new_user_session_path %></li>
<% end %>

app/views/layouts/_pew_footnote.html.erb
<% content_for :footer do %>
  <div class="row">
    <div class="col-lg-12 col-md-12 footnote">
      <small>* The data from Pew has been simplified for graphical representation as follows: Responses in the
        categories
        of
        'Other Christian' and 'Other World Religion' have been combined into 'Other Religion'. Unaffiliated has been
        changed
        to 'None'. Responses in the category of 'Don’t Know/Refused' have been added to 'None'. The responses Mormon,
        Buddhist, and Hindu which were originally <0.5 have been rounded up to 0.5 each.
      </small>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="author" href="/humans.txt" />
  <title><%= content_for?(:title) ? yield(:title) : 'Invocations Online' %><%= content_for?(:page_name) ? " - #{yield(:page_name)}" : '' %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Invocations Online' %>">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container-fluid'>
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12">
        <header>
          <%= render 'layouts/navigation' %>
        </header>
      </div>
    </div>
    <div class="row">
      <div class="main col-md-12">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12">
      <footer class="clearfix">
        <div class="footer-nav-wrapper">
          <div class="col-lg-5 col-sm-7 col-md-5 footer-nav">
            <ul class="small" role="navigation">
              <li><%= link_to 'Terms and Conditions', page_path('volunteer') %></li>
              <li><%= link_to 'Privacy Policy', page_path('volunteer') %></li>
              <li><%= link_to 'Contact Us', contact_path %></li>
                <% if user_signed_in? %>
                  <% if current_user.has_role?(:admin) %>
                    <li><%= link_to 'Support', 'https://invocationsonline.freshdesk.com' %></li>
                  <% end %>
                <% end %>
            </ul>
          </div>
          <div class="col-lg-2 col-lg-offset-5 col-sm-3 col-sm-offset-2 col-md-3 col-md-offset-4 copyright">&copy; <%= Time.now.strftime('%Y') %> CFFC</div>
        </div>
        <%= yield(:footer) %>
      </footer>
    </div>
  </div>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= yield(:scripts) %>
  <% if user_signed_in? %>
    <% if current_user.has_role?(:admin) %>
      <script type="text/javascript" src="https://s3.amazonaws.com/assets.freshdesk.com/widget/freshwidget.js"></script>
      <script type="text/javascript">
        FreshWidget.init("", {
            "queryString": "&widgetType=popup",
            "widgetType": "popup",
            "buttonType": "text",
            "buttonText": "Support",
            "buttonColor": "white",
            "buttonBg": "#006063",
            "alignment": "4",
            "offset": "235px",
            "formHeight": "500px",
            "url": "https://invocationsonline.freshdesk.com"
        } );
      </script>
    <% end %>
  <% end %>
</body>
</html>